language: java

notifications:
    email: false

sudo: false

branches:
  only:
      - master

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk:
    - openjdk7
    - openjdk8
    - oraclejdk8
    - oraclejdk9

