language: java

cache:
  directories:
    - "$HOME/.m2"

notifications:
    email: false

sudo: false

branches:
  only:
      - master

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk:
    - openjdk7
    - openjdk8
    - oraclejdk8
    - oraclejdk9

install:
    - mv .settings.xml $HOME/.m2/settings.xml
    - mvn dependency:go-offline
    - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

